$('.owl-carousel').owlCarousel({
    loop:true,
	stagePadding: 0,
    margin:10,
    nav:false,
	autoplay:1000,
	center:true,
    responsive:{
        0:{
            items:5
        },
        600:{
            items:5
        },
        1000:{
            items:5
        }
    }
})